### ISSUE TITLE
请问一下无法抽取塔罗牌这是什么问题

### ISSUE THREAD

**Issue by Montpellier2020** [diyigemt/arona#10]
![image](https://user-images.githubusercontent.com/126932432/224308252-300ebb63-561f-4113-9686-7ffe04d8de23.png)
![image](https://user-images.githubusercontent.com/126932432/224308312-b1981328-84e5-4e6e-b677-fadb85e46a34.png)
报错的就这些，还麻烦大佬解答一下，谢谢了

**Comment by Montpellier2020** [comment]
补充一下 我这边机器人用的是IPAD协议登录的，是不是和机器人登录的协议有关？还请大佬查看一下，谢谢了

**Comment by diyigemt** [comment]
没有其他的了吗，这个看起来像是没登陆机器人在下载塔罗牌图片的时候出错尝试通过没登陆的机器人向管理员发消息
但是没登陆机器人怎么接收到塔罗牌的指令的
哦我发现了
你是不是没把数据库覆盖上去
是在查询塔罗牌解读的时候出错的

**Comment by Montpellier2020** [comment]
> 没有其他的了吗，这个看起来像是没登陆机器人在下载塔罗牌图片的时候出错尝试通过没登陆的机器人向管理员发消息 但是没登陆机器人怎么接收到塔罗牌的指令的 哦我发现了 你是不是没把数据库覆盖上去 是在查询塔罗牌解读的时候出错的

您好，我已经解决了，貌似是没更新的原因，我自己笨比了，感谢大佬解答
