### ISSUE TITLE
关闭防侠提醒功能后仍会推送

### ISSUE THREAD

**Issue by walkonbothsides** [diyigemt/arona#2]
![Screenshot_2023-01-31-09-34-53-62_d575fd10b440f1adc203f4f6bca6eb00](https://user-images.githubusercontent.com/35983178/215637140-7a8fda60-c954-4c0f-96cb-88b7d76cd563.jpg)
![Screenshot_2023-01-31-09-33-56-47_9d26c6446fd7bb8e41d99b6262b17def](https://user-images.githubusercontent.com/35983178/215637153-b7c24750-5fda-4ad6-9ef3-73e64a50b408.jpg)

**Comment by diyigemt** [comment]
这个配置文件是什么时候修改的，配置文件需要在mirai-console停止的状态下修改才有效果

**Comment by walkonbothsides** [comment]
> 这个配置文件是什么时候修改的，配置文件需要在mirai-console停止的状态下修改才有效果

是停止后修改的没错

**Comment by diyigemt** [comment]
> > 这个配置文件是什么时候修改的，配置文件需要在mirai-console停止的状态下修改才有效果
> 
> 是停止后修改的没错

你可以试着在arona-service.yaml里把它整个关了

**Comment by walkonbothsides** [comment]
> 
> 
> 
> > > 这个配置文件是什么时候修改的，配置文件需要在mirai-console停止的状态下修改才有效果
> > 
> > 是停止后修改的没错
> 
> 你可以试着在arona-service.yaml里把它整个关了

成功关闭服务了

**Comment by 1301715759** [comment]
> > > 这个配置文件是什么时候修改的，配置文件需要在mirai-console停止的状态下修改才有效果
> > 
> > 
> > 是停止后修改的没有错误
> 
> 你可以试试在arona-service.yaml里把它整个关了

但是每次更新后（似乎是卡池更新）都会自动把这个配置文件还原到默认，就是自动报警，已经好几次了

**Comment by diyigemt** [comment]
> > > > 这个配置文件是什么时候修改的，配置文件需要在mirai-console停止的状态下修改才有效果
> > > 
> > > 
> > > 是停止后修改的没有错误
> > 
> > 
> > 你可以试试在arona-service.yaml里把它整个关了
> 
> 但是每次更新后（似乎是卡池更新）都会自动把这个配置文件还原到默认，就是自动报警，已经好几次了

试试1.0.14看看

**Comment by pilgrim773** [comment]
我有一个类似的问题，今天调试其他插件的时候需要反复重启mirai-console，每次重启好大概10秒后，所有配置了arona服务的群都会发一次防侠。我只改了notify里的第一个为false。无效。
这问题根源是什么呢

**Comment by diyigemt** [comment]
> 我有一个类似的问题，今天调试其他插件的时候需要反复重启mirai-console，每次重启好大概10秒后，所有配置了arona服务的群都会发一次防侠。我只改了notify里的第一个为false。无效。 这问题根源是什么呢

`enableEveryDay`只控制是否每日固定时间发送活动提醒
而`enableJP`和`enableEN`分别控制是否在活动即将结束时提醒
你关闭`enableEveryDay`并不会影响每次启动时获取到活动即将结束的信息，而`enableJP`和`enableEN`又开着，所以才会发送防侠信息
是我文档写得不太清楚，如果要完全关闭应该去`arona-service.yml`那边关
