### ISSUE TITLE
权限设置不起作用

### ISSUE THREAD

**Issue by Yuk-0v0** [diyigemt/arona#20]
版本号为[Release v1.0.14+20230310](https://github.com/diyigemt/arona/releases/tag/v1.0.14%2B20230310)

表现情况为给群组权限但仍然无法响应，同样的权限设置没变退回[Release v1.0.14](https://github.com/diyigemt/arona/releases/tag/v1.0.14)
后一切正常

```
/perm add gxxx net.diyigemt.arona:*
```

**Comment by diyigemt** [comment]
能提供chat-command的版本号和console的版本号吗，
如果是chat-command的版本是0.6.0能不能提供一下执行指令后的控制台输出，如果不是0.6.0，在[这里](https://github.com/project-mirai/chat-command/releases/tag/v0.6.0)更新以后也请提供一下执行指令后的控制台输出

顺带一提插件是不走console本身的权限控制的，如果要控制权限可以通过配置文件 arona.yaml 的groups和tempMessageIgnoreType控制

我在1.0.14版本全新安装并执行
```bash
/perm add gxxx net.diyigemt.arona:*
```
后也无法响应，没能复现你提到的情况

**Comment by Yuk-0v0** [comment]
### 环境相关
chat-command是v0.5.0，看了下[Maven仓库](https://mvnrepository.com/artifact/net.mamoe/chat-command)里开发者并没有提交GitHub上的v0.6.0（啊这
安装走的是 [Mirai官方教程](https://github.com/mamoe/mirai/blob/dev/docs/ConsoleTerminal.md#%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85%E5%AE%98%E6%96%B9%E6%8F%92%E4%BB%B6)
具体环境如下
```
Running MiraiConsole v2.14.0, built on 2023-02-06 06:25:21.
Frontend Terminal: version 2.14.0, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: Chat Command v0.5.0, ba-activity-pusher v1.0.14, mirai-api-http v2.9.1, mirai-login-solver-sakura v0.0.9, MCL Addon v2.1.1
```
v0.5.0的执行指令后的控制台无异常输出..

### 配置相关
是已经在arona.yaml中配置了groups和managerGroup，tempMessageIgnoreType设置的是ALL
表现情况是managerGroup指定的qq可以在群组中正常响应，群组内其他成员无法响应

**Comment by diyigemt** [comment]
感谢 大概知道问题在哪了 吃个饭就修

**Comment by diyigemt** [comment]
fix at [1.0.14+20230325](https://github.com/diyigemt/arona/releases/tag/v1.0.14%2B20230325)
