### ISSUE TITLE
情人节攻略图片错误

### ISSUE THREAD

**Issue by Nohara3** [diyigemt/arona#22]
/攻略 日服情人节出来的图是FSCT攻略战的图，并不是情人节的攻略图
/攻略 颜艺出来的图是一张不完整的图片
还有个小问题就是为什么睦月的攻略图片是歪的

**Comment by diyigemt** [comment]
修好了

睦月那张是为了对抗tx的和谐没办法，我也不知道戳到哪的g点了，同理如果发现其他也是歪的理由一样
最离谱的是水静子，个人介绍里的`生机**勃勃**`是g点
