### ISSUE TITLE
部分攻略图片错误

### ISSUE THREAD

**Issue by Nohara3** [diyigemt/arona#26]
1.指令斯大罗所返回的图片，评分图是温泉斯大萝的
2.指令mika/未花/弥香所返回的图片，子技能Benedictio数值错误与schaledb资料不符
3.指令轮椅/日鞠所返回的图片，子技能数值描述与schaledb以及游戏内都不符
4.指令FSCT攻略战，在4月时还能查询并返回对应的图片，5月后，攻略杂图里已经没有该指令了，也无法查询到对应的攻略图片了
5./攻略 日服室内球命令返回的是黑白总力的图片
6./攻略 炮台的图片中的基本技能，t2爱用品一栏还是日文
7./攻略 日服/国际服人权所返回的图片，是十字神名商店推荐升星图而不是之前的人权图

**Comment by diyigemt** [comment]
1、2、3我看了一圈，都是错的，慢慢来吧，最慢明天中午能修好
4、5 修好了
6 中文翻译来源是https://ba.game-db.tw/ -> schaledb  如果这两都没翻译那就没翻译了，我也不敢乱译，至少生成的时候没有中文，最近猫佬更新6.0了可以顺便加上
7 修了
感谢反馈
