### ISSUE TITLE
请问自行编辑Image表无效是正常的吗

### ISSUE THREAD

**Issue by KuraiKama** [diyigemt/arona#28]
想自己添加一些别名进去，但是好像没有效果

**Comment by diyigemt** [comment]
别名配置看这节
https://doc.arona.diyigemt.com/config/base-config#arona-trainer-yml
不停机修改看这节
https://doc.arona.diyigemt.com/config/base-config#_5-trainer-config-yml%E9%85%8D%E7%BD%AE%E8%AF%A6%E8%A7%A3

image表是由我管理的中央服务器维护的，只写不读

**Comment by KuraiKama** [comment]
十分感谢
