### ISSUE TITLE
raid镜像返404

### ISSUE THREAD

**Issue by hundun000** [diyigemt/arona#29]
我的mirai还能用，欲使用该插件，需要通过镜像获取资源。
console日志：
> W/ba-activity-pusher: 获取数据源: RAID 失败，请检查网络连接

人工浏览器尝试`https://schaledb.brightsu.cn/data/raids.min.json`为404

**Comment by diyigemt** [comment]
收到，找时间修一下吧，这个其实没什么影响

**Comment by hundun000** [comment]
哦，之前bot没响应我还以为是因为这个。刚刚发现是配置有字段漏配了，现在是能用了，不影响。

**Comment by diyigemt** [comment]
fix at v1.1.0
