### ISSUE TITLE
/活动 jp功能无法正常使用

### ISSUE THREAD

**Issue by Nohara3** [diyigemt/arona#3]
![image](https://user-images.githubusercontent.com/124423679/216753011-85e9a7f4-31ea-4611-95e0-870984a14dc6.png)
![image](https://user-images.githubusercontent.com/124423679/216753035-beea8be2-e6ba-43c8-8b00-9c600514bb45.png)
![image](https://user-images.githubusercontent.com/124423679/216753055-fea9c1a0-52a1-41e9-9acf-ef1f9862c664.png)

/活动 en正常没有任何问题

**Comment by diyigemt** [comment]
这... 怎么说好呢
有一个OOM错误，意味着内存不够了
我估计是最近国际服的活动不多，但是日服的活动多，我又用了超分辨率的方法让整张图好看点，所以二者加持下生成图片的内存不够了，试着给多点内存？

**Comment by diyigemt** [comment]
这... 怎么说好呢
有一个OOM错误，意味着内存不够了
我估计是最近国际服的活动不多，但是日服的活动多，我又用了超分辨率的方法让整张图好看点，所以二者加持下生成图片的内存不够了，试着给多点内存？
