### ISSUE TITLE
/攻略 纱织的图片疑似被tx屏蔽

### ISSUE THREAD

**Issue by Nohara3** [diyigemt/arona#30]
![Q {R0${M1Y_}6_6H8378_0M](https://github.com/diyigemt/arona/assets/124423679/671d2a8e-f39d-468c-80a6-f968657be89c)
后台看发送是正常的，qq上却没收到，非群聊风控因为用的是手表协议私聊，且其他图片是正常的

**Comment by diyigemt** [comment]
草 这里面有什么r18要素吗
修了
