### ISSUE TITLE
自定义发情监测词

### ISSUE THREAD

**Issue by Andy-Chuck** [diyigemt/arona#33]
希望能自定义发情监测词，如果支持自定义，将是一个很好的关键词回复功能

**Comment by diyigemt** [comment]
或许可以试试其他插件?
https://mirai.mamoe.net/topic/1193/%E4%B8%80%E4%B8%AA%E7%AE%80%E6%98%93%E7%9A%84%E8%87%AA%E5%8A%A8%E5%9B%9E%E5%A4%8D%E6%8F%92%E4%BB%B6
https://mirai.mamoe.net/topic/636/console-%E8%87%AA%E5%8A%A8%E5%AE%9A%E4%B9%89%E5%9B%9E%E5%A4%8D%E6%8F%92%E4%BB%B6/2
毕竟她不是主要干这个的，这也是多插件环境存在的意义

**Comment by Andy-Chuck** [comment]
谢谢指点
