### ISSUE TITLE
/攻略 plana 已被和谐

### ISSUE THREAD

**Issue by Andy-Chuck** [diyigemt/arona#36]
看了眼数据文件夹，下载成功了，但是发不出去
该说不说雀食太涩了🥵

**Comment by diyigemt** [comment]
🥵🥵🥵能不能提供同样色但是没被和谐的我换上去

**Comment by Andy-Chuck** [comment]
不太了解情况，昨天自己的机器人和隔壁群的旧版机器人都不能把这张图发出来，现在似乎又正常了


有种看心情屏蔽的感觉

**Comment by Andy-Chuck** [comment]
不太了解情况，昨天自己的机器人和隔壁群的旧版机器人都不能把这张图发出来，现在似乎又正常了

有种看心情屏蔽的感觉
![Screenshot_2023-08-06-14-37-54-786_com tencent mo](https://github.com/diyigemt/arona/assets/54295429/6100dd4a-20ef-4314-8939-aab8a68b0234)
![Screenshot_2023-08-06-14-38-43-294_com tencent mo](https://github.com/diyigemt/arona/assets/54295429/1b130769-3aae-4f02-92f5-5299174c4e77)

**Comment by diyigemt** [comment]
我也没法子，总不能给tx塞钱叫他不要屏蔽吧

**Comment by Andy-Chuck** [comment]
目前就保持原样吧，在pixiv找了一圈，和原图同样涩的大多数也是被屏蔽的🥵
