### ISSUE TITLE
能否为NGA图片转发功能提供一个频率控制设置

### ISSUE THREAD

**Issue by Nohara3** [diyigemt/arona#37]
比如多个QQ群，以每隔1分钟的频率，逐个发送，而不是同时给多个群发送，同时给多个群转发多张图疑似容易被tx盯上

**Comment by diyigemt** [comment]
那加上吧，不过我觉得没啥用

**Comment by diyigemt** [comment]
试一下最新的Pre-Release? https://github.com/diyigemt/arona/releases/tag/v1.1.2-RC

**Comment by Nohara3** [comment]
实测最新的v1.1.2版本没有问题，时间间隔和合并转发功能正常，辛苦了
