### ISSUE TITLE
建议增加指令/攻略 国服活动，以及未找到下一期的国服活动攻略图

### ISSUE THREAD

**Issue by Nohara3** [diyigemt/arona#40]
![image](https://github.com/diyigemt/arona/assets/124423679/7add2a1e-9e99-4cf5-b13f-ff4b8c3d8866)
这期活动攻略图，/攻略 杂图里未找到，建议增加指令 /攻略 国服活动

**Comment by diyigemt** [comment]
加是加上了，但是当时猫佬也没开始做攻略，所以只有复刻的资料，多了个奇观的三森进去

**Comment by Nohara3** [comment]
好的 不影响
