### ISSUE TITLE
指令执行被拦截, 原因: InterceptedReasonData(message=权限不足或功能未启用)

### ISSUE THREAD

**Issue by Ning-Off** [diyigemt/arona#43]
![image](https://github.com/diyigemt/arona/assets/102615856/3c8e0bd8-e48f-49b7-9ef2-d4d8908f6d75)
![image](https://github.com/diyigemt/arona/assets/102615856/807d08d6-d622-4fd2-b4f2-4dc1a7e02b45)
已j进行去权限给予，但是仍无权限。

**Comment by Andy-Chuck** [comment]
有可能是功能未启用？

**Comment by diyigemt** [comment]
1.检查`arona.yml`里的`groups`里边有没有这个群
2.检查`arona-service.yml`里的`抽卡十连`是不是`true`

**Comment by Ning-Off** [comment]
我这边解决了，但是有个小问题，arona.yml中的group无法通过指令进行添加，只能停止bot运行后进行手动增加群号。

**Comment by diyigemt** [comment]
因为.. 本来也不能啊
group是插件自己内部的权限控制，`/permission`是console的权限控制
不过倒是可以考虑全用console的
