### ISSUE TITLE
当前arona似乎不适配mirai版本大于2.15？

### ISSUE THREAD

**Issue by superexboom** [diyigemt/arona#46]
我前两天升级了mirai到2.16，去使用签名服务器，但是在升级之后出现启动报错，看报错内容是arona启动失败了，之前2.15一切正常，所以在寻思是不是版本过高的问题。不清楚作者是否还有心情兼容高版本，就当留个提醒别人的方式吧（如果有同版本但是能正常运行的，还需请教下）。

**Comment by diyigemt** [comment]
啊? 我看官方的latest release还是2.15啊
2.16还是RC状态，以及报错报啥能发我不，你光说我也不知道发生啥了

**Comment by superexboom** [comment]
这是arona的报错：https://pastebin.com/i0M51w3t

这是skia的报错：https://pastebin.com/DkpSUgfN
↑虽然说有个skia的报错，这个我无法确定是有arona之后出现的，还是平时就有，这个并没有留意
编辑：确认平时也报错

mirai在初始化阶段就直接报错退出了
（已更换pastebin）

**Comment by diyigemt** [comment]
翻了一下更新日志没提到这个问题，然后去翻了commit记录
说来也搞笑，他们修了一个去年8月的issue，导致我一直以来的加载方式炸了，但是他们没提供迁移文档，我自己琢磨一下
至于skia这个报错，我没依赖skia

**Comment by superexboom** [comment]
> 翻了一下更新日志没提到这个问题，然后去翻了commit记录 说来也搞笑，他们修了一个去年8月的issue，导致我一直以来的加载方式炸了，但是他们没提供迁移文档，我自己琢磨一下 至于skia这个报错，我没依赖skia

好的感谢，skia目前我好像也并没有依赖mod，至少目前好像并没有其他插件出错，就不管他了，it just work。

**Comment by diyigemt** [comment]
加上了 [v1.1.4-RC](https://github.com/diyigemt/arona/releases/tag/v1.1.4-RC)

**Comment by superexboom** [comment]
感谢更新，已测试，目前没有可见的问题，后续如果有报错再反馈，再次感谢！
