### ISSUE TITLE
无论用什么版本的arona插件打开mcl控制台就会报错

### ISSUE THREAD

**Issue by Montpellier2020** [diyigemt/arona#48]
![image](https://github.com/diyigemt/arona/assets/126932432/6d5d9e29-526c-48c2-a553-fc07f3e2553e)
大概全都报如上错误

**Comment by Montpellier2020** [comment]
麻烦大佬能看一下了，谢谢了

**Comment by diyigemt** [comment]
还装有其他插件吗

**Comment by Montpellier2020** [comment]
> 还装有其他插件吗

我现在没问题了，应该是系统莫名其妙的bug，不好意思麻烦大佬了

**Comment by diyigemt** [comment]
这 看来我得加个issue template了
