### ISSUE TITLE
每次停止再重启mirai-console都会加载初次填写的配置文件

### ISSUE THREAD

**Issue by pilgrim773** [diyigemt/arona#5]
想知道是不是写数据库里去了，我想加点适配的群组，结果每次都被刚安装好的第一批数据覆盖yaml文件

**Comment by Goldmifan** [comment]
关闭控制台的时候再填写，如果你是bot在运作的时候改配置文件会出现重启之后变回默认配置（我反正是这样）关闭控制台之后再修改配置再启动就不会出现这种情况了

**Comment by pilgrim773** [comment]
感谢，解决了
