### ISSUE TITLE
运行./mcl时报错

### ISSUE THREAD

**Issue by Shigaharuki3012** [diyigemt/arona#53]
您好，当我运行`./mcl`，显示：
```
@CyberpsycodeMacBook-Air mcl % ./mcl
 16:31:01 [ERROR] Failed to verify package "org.bouncycastle:bcprov-jdk15on"
  16:31:01 [ERROR] java.net.ConnectException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:951)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
	at org.itxtech.mcl.component.Repository.httpGet(Repository.java:211)
	at org.itxtech.mcl.component.Repository.httpGet(Repository.java:206)
	at org.itxtech.mcl.component.Repository.fetchPackage(Repository.java:84)
	at org.itxtech.mcl.module.builtin.RepoCache$RepoWithCache.fetchPackage(RepoCache.java:88)

```
java的版本为JDK17，但是无论是17还是21均是以上报错。

**Comment by Ning-Off** [comment]
你是不是没有进行环境配置呢？检查一下更新java包后环境配置是否是和当前包版本一致的。

**Comment by Ning-Off** [comment]
你这里显示的好像是找不到java15on版本，你应该是安装了新版本java但是环境配置仍然指向老版本java。先按照手册更新一下环境配置看看。

**Comment by Shigaharuki3012** [comment]
> 你这里显示的好像是找不到java15on版本，你应该是安装了新版本java但是环境配置仍然指向老版本java。先按照手册更新一下环境配置看看。

您是指解压mcl文件夹时里面的config.json文件里的配置吗？我也改成java17on了，但是报错仍然是上面所示。

**Comment by Ning-Off** [comment]
> 
并不是，是你系统的环境配置。MAC系统的版本我并不熟悉，但是看报错的话还是使用了java15on版本。

**Comment by Shigaharuki3012** [comment]
> > 
> 
> 并不是，是你系统的环境配置。MAC系统的版本我并不熟悉，但是看报错的话还是使用了java15on版本。


实在抱歉qaq，我是个新手.....所以想再请教一下，我安装的是jdk17(java 17)的版本，怎么会使用到java15on的版本呢？
您提到我的环境配置，值的是我的bash_profile(或者zshrc)文件里面的设置吗？

同时，我发现也有一些人也跟我有一样的问题，有其他人指路 https://mirai.mamoe.net/topic/1084，然而这个网站似乎已经登不进去了。

**Comment by Ning-Off** [comment]
如果你使用的是windows系统可以跟随这个视频去进行环境的重新配置：https://www.bilibili.com/video/BV1vy4y127mL/?spm_id_from=333.337.search-card.all.click&vd_source=47be251a78bca5c8ecacd9ec7c194499
但是你用户名里面出现了MacBook-Air，我怀疑是mac系统，很抱歉没有在mac系统中进行过环境变量配置。
这个视频可能会帮助你进行mac系统环境变量的配置：https://www.bilibili.com/video/BV1ag411k7Tk/?spm_id_from=333.337.search-card.all.click&vd_source=47be251a78bca5c8ecacd9ec7c194499
如果你没有解决的话可以去阿里云看看学生的免费云服务器进行重新搭建。

**Comment by diyigemt** [comment]
看起来是安装过程出问题了，重装mirai-console试试?
ConnectException是网络连接除了问题，可能是安装的时候依赖下载不全

**Comment by Shigaharuki3012** [comment]
> 看起来是安装过程出问题了，重装mirai-console试试? ConnectException是网络连接除了问题，可能是安装的时候依赖下载不全

谢谢您的回复。我之前也重新装了几遍，但是仍然是这样的问题，显示java15on无法验证。
我其实是想部署arona机器人，网址见https://doc.arona.diyigemt.com/guide/glossary。
而其中的安装步骤都是基于MCL来完成的，因此仅仅安装mirai-console也许不能成功。

**Comment by Shigaharuki3012** [comment]
> 如果你使用的是windows系统可以跟随这个视频去进行环境的重新配置：https://www.bilibili.com/video/BV1vy4y127mL/?spm_id_from=333.337.search-card.all.click&vd_source=47be251a78bca5c8ecacd9ec7c194499 但是你用户名里面出现了MacBook-Air，我怀疑是mac系统，很抱歉没有在mac系统中进行过环境变量配置。 这个视频可能会帮助你进行mac系统环境变量的配置：https://www.bilibili.com/video/BV1ag411k7Tk/?spm_id_from=333.337.search-card.all.click&vd_source=47be251a78bca5c8ecacd9ec7c194499 如果你没有解决的话可以去阿里云看看学生的免费云服务器进行重新搭建。

谢谢回复！
是的，我是mac系统，而且我在此之前的确也配置了跟视频中一样的环境变量，然而问题似乎不是出在环境变量上面。

**Comment by diyigemt** [comment]
https://github.com/iTXTech/mirai-console-loader/issues/190
我在mcl的仓库看到了一个类似的问题，可以试试换个jdk发行版

**Comment by Shigaharuki3012** [comment]
> [iTXTech/mirai-console-loader#190](https://github.com/iTXTech/mirai-console-loader/issues/190) 我在mcl的仓库看到了一个类似的问题，可以试试换个jdk发行版

谢谢回复！
我根据https://zhuanlan.zhihu.com/p/436493583
的方式利用homebrew安装了openjdk17版本，结果仍然是无法验证java15on以及无法连接qaq。

**Comment by diyigemt** [comment]
可以截图看一下`libraries`文件夹下的情况吗，最好包括里面文件的大小

**Comment by Ning-Off** [comment]
我还是觉得是你的环境变量指向配置错误了，或者你安装新版本java后没有改好一些特定值，导致环境变量调用时选用的Java15on跟你现在安装的版本不一致。

**Comment by Ning-Off** [comment]
毕竟你最大的报错是:“faild to verify package"org.bouncycastle:bcprov-jdk15on"”
也就是验证包Java15on失败。
如果你多次更新Java版本但是报错一致，我认为你现在要做的是彻底检查与环境变量配置有关的任何东西。

**Comment by diyigemt** [comment]
> 毕竟你最大的报错是:“faild to verify package"org.bouncycastle:bcprov-jdk15on"” 也就是验证包Java15on失败。 如果你多次更新Java版本但是报错一致，我认为你现在要做的是彻底检查与环境变量配置有关的任何东西。

这个`org.bouncycastle:bcprov-jdk15on`是`libraries`文件夹下的一个依赖库，和jdk本身没太大关系

**Comment by Shigaharuki3012** [comment]
> > 毕竟你最大的报错是:“faild to verify package"org.bouncycastle:bcprov-jdk15on"” 也就是验证包Java15on失败。 如果你多次更新Java版本但是报错一致，我认为你现在要做的是彻底检查与环境变量配置有关的任何东西。
> 
> 这个`org.bouncycastle:bcprov-jdk15on`是`libraries`文件夹下的一个依赖库，和jdk本身没太大关系

您指的是mcl压缩包解压后的lib文件夹吗，我截图如下：
![2276393138](https://github.com/diyigemt/arona/assets/105692461/c4526dd5-024c-446d-aff4-163b562a23bd)
![3696035646](https://github.com/diyigemt/arona/assets/105692461/820c6288-830f-4e7d-8bd2-33fd1731d2d2)

**Comment by Shigaharuki3012** [comment]
> 毕竟你最大的报错是:“faild to verify package"org.bouncycastle:bcprov-jdk15on"” 也就是验证包Java15on失败。 如果你多次更新Java版本但是报错一致，我认为你现在要做的是彻底检查与环境变量配置有关的任何东西。

嗯嗯，我将我的环境变量配置贴在下方，您可以看看：
```
source ~/.bash_profile
export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles
export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"
export CPPFLAGS="-I/opt/homebrew/opt/openjdk@17/include"
export JAVA_HOME=$(/usr/libexec/java_home -v17.0.9)
```
                                                  
这是mac上管理环境变量的文件中的内容（.zshrc）

**Comment by diyigemt** [comment]
等下? mcl压缩包？
我记得我安装指南第一行就是推荐用 https://github.com/iTXTech/mcl-installer 安装，而不是自己处理mcl
如果是M1M2啥的芯片，要用mcl-installer-1.0.7-macos-aarch64，否则就是mcl-installer-1.0.7-macos-amd64

**Comment by Shigaharuki3012** [comment]
> 等下? mcl压缩包？ 我记得我安装指南第一行就是推荐用 https://github.com/iTXTech/mcl-installer 安装，而不是自己处理mcl 如果是M1M2啥的芯片，要用mcl-installer-1.0.7-macos-aarch64，否则就是mcl-installer-1.0.7-macos-amd64

非常抱歉这么晚回复。对的，指南上确实这么写，我一开始也是使用您的方式安装，但是似乎论坛关闭，所以运行mcl-installer-1.0.7-macos-aarch64（也就是我自己的版本，我是M2芯片）的时候会显示错误。具体可见我与另一位大佬提的issue：https://github.com/iTXTech/mcl-installer/issues/68

也因此他建议我手动安装mcl，而不是使用mcl-installer

**Comment by diyigemt** [comment]
我试着手动安装mcl，并没有遇到这个问题，能否提供从执行`./mcl`这个命令开始的所有log

**Comment by Shigaharuki3012** [comment]
> 我试着手动安装mcl，并没有遇到这个问题，能否提供从执行`./mcl`这个命令开始的所有log

如果您是指log文件的话，我似乎并没有在运行之后找到。然而今天运行`./mcl`时，突然可以成功下载java15on了（今天刚好mamoe的论坛开放了），但是显示如下：
```
2023-11-09 10:23:59 I/main: Backend: version 2.16.0, built on 2023-10-20 06:28:10.
2023-11-09 10:23:59 I/main: Frontend Terminal: version 2.16.0, provided by Mamoe Technologies
2023-11-09 10:23:59 I/main: Welcome to visit https://mirai.mamoe.net/
2023-11-09 10:24:17 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-11-09 10:24:17 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-11-09 10:24:17 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-11-09 10:24:17 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-11-09 10:24:17 I/main: 2 plugin(s) enabled.
========================================== [ End User Readme ] ===========================================
最终用户须知有更新，在您继续使用前，您必须完整阅读新的用户须知。
======================================= [ mirai-console.greeting ] =======================================
欢迎使用 mirai-console。
在您正式开始使用 mirai-console 前，您需要完整阅读此用户须知。

此用户须知包含 mirai-console 本体及其所安装的插件的用户须知。
当相关的最终用户须知更新时，mirai-console 只会显示已更新部分，而不会重新完整显示整个用户须知。
Enter to continue> 

```
这是否是成功的标志？因为在arona文档中，它最终提示“mirai-console started successfully”才是完成，并且我在光标处输入“stop”时，mcl并未停止运行。

还有一个问题是，unidbg-fetch-qsign的资源似乎没掉了（https://github.com/fuqiuluo/unidbg-fetch-qsign）QAQ

**Comment by diyigemt** [comment]
算是成功了，只需要跟着引导走完就行了，unidbg-fetch-qsign可以用这个代替
https://github.com/MrXiaoM/qsign/tree/mirai

**Comment by Shigaharuki3012** [comment]
> 算是成功了，只需要跟着引导走完就行了，unidbg-fetch-qsign可以用这个代替 https://github.com/MrXiaoM/qsign/tree/mirai

感谢回复！
目前我使用onekey来使用unidbg-fetch-qsign，然而似乎我的mcl并未成功运行，以下是我在能打开mcl后生成的log文件：
```
2023-11-09 12:24:19 I/fix-protocol-version: protocol commands: info, load, fetch
example:
  protocol info
  protocol load ANDROID_PHONE
  protocol fetch ANDROID_PAD 8.9.63

2023-11-09 12:24:19 I/fix-protocol-version: 当前各登录协议版本日期: 
ANDROID_PHONE  8.9.63.11390  2023-05-26T10:46:18+08:00
ANDROID_PAD    8.9.58.11170  2023-05-19T11:35+08:00
ANDROID_WATCH  2.0.8         2019-06-03T20:25:31+08:00
IPAD           8.9.50.611    2023-02-16T15:10:14+08:00
MACOS          6.8.2.21241   2022-03-14T11:11:35+08:00

2023-11-09 12:24:19 I/fix-protocol-version: 当前签名服务配置信息: 
v8.9.63 by fuqiuluo/unidbg-fetch-qsign from http://127.0.0.1:12780

缺少 v8.9.58 配置
2023-11-09 12:24:19 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-11-09 12:24:19 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-11-09 12:24:19 I/main: 5 plugin(s) enabled.
2023-11-09 12:29:55 E/main: Failed to init MiraiConsole.

```
最后一行显示并未成功初始化mcl，并且我在启动mcl后的命令行不论输入什么，最后也只会显示`enter to continue>`。
启动mcl后显示如下：
```
2023-11-09 18:04:52 I/fix-protocol-version: 当前各登录协议版本日期: 
ANDROID_PHONE  8.9.63.11390  2023-05-26T10:46:18+08:00
ANDROID_PAD    8.9.58.11170  2023-05-19T11:35+08:00
ANDROID_WATCH  2.0.8         2019-06-03T20:25:31+08:00
IPAD           8.9.50.611    2023-02-16T15:10:14+08:00
MACOS          6.8.2.21241   2022-03-14T11:11:35+08:00

2023-11-09 18:04:52 I/fix-protocol-version: 当前签名服务配置信息: 
v8.9.63 by fuqiuluo/unidbg-fetch-qsign from http://127.0.0.1:12780

缺少 v8.9.58 配置
2023-11-09 18:04:52 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-11-09 18:04:52 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-11-09 18:04:52 I/main: 5 plugin(s) enabled.
========================================== [ End User Readme ] ===========================================
最终用户须知有更新，在您继续使用前，您必须完整阅读新的用户须知。
======================================= [ mirai-console.greeting ] =======================================
欢迎使用 mirai-console。
在您正式开始使用 mirai-console 前，您需要完整阅读此用户须知。

此用户须知包含 mirai-console 本体及其所安装的插件的用户须知。
当相关的最终用户须知更新时，mirai-console 只会显示已更新部分，而不会重新完整显示整个用户须知。
Enter to continue> 
```

**Comment by diyigemt** [comment]
"在您正式开始使用 mirai-console 前，您需要完整阅读此用户须知。"

Enter to continue的中文翻译是: 按下回车继续

意思是，你需要看完整个用户许可协议，才能完成安装

**Comment by Shigaharuki3012** [comment]
> "在您正式开始使用 mirai-console 前，您需要完整阅读此用户须知。"
> 
> Enter to continue的中文翻译是: 按下回车继续
> 
> 意思是，你需要看完整个用户许可协议，才能完成安装

实在不好意思....没有注意到需要先回车阅读完才能完成，我以为这样就到了命令行界面了。
非常感谢您和上面那位大佬的解答。
