### ISSUE TITLE
后端测试公告不间断发送

### ISSUE THREAD

**Issue by Fitz0527** [diyigemt/arona#58]
### 问题描述

大圣快收了神通把，怕消息频率过高已经暂时下线了
![image](https://github.com/diyigemt/arona/assets/30644949/2db6363e-8a82-442c-95aa-5d41fc79fa6e)

### arona 版本

1.1.4-RC2

**Comment by zero1234888** [comment]
+1，大佬收了神通吧，qq被打爆了

**Comment by Ning-Off** [comment]
樂

**Comment by Ning-Off** [comment]
我的到还没事，但是一看99+给我看麻了。

**Comment by huvz04** [comment]
绷

**Comment by diyigemt** [comment]
修好了修好了

**Comment by Ning-Off** [comment]
> 修好了修好了

听说公告里面让做什么都可以~
那要不来女装谢罪吧~（不是）
樂

**Comment by diyigemt** [comment]
啊哈哈
