### ISSUE TITLE
请问api基址更改后自行部署版的还能不能正常使用

### ISSUE THREAD

**Issue by Nuist666** [diyigemt/arona#59]
### 问题描述

你好！请问api基址更改后，在24年2月23日以后自行部署版的能不能正常使用呢  
![image](https://github.com/diyigemt/arona/assets/104258411/a29e6e19-61c5-4eb8-8c73-8afe7afc0ed9)

### arona 版本

1.1.4

**Comment by diyigemt** [comment]
用来吓人的(

**Comment by Nuist666** [comment]
啊哈哈，还能用的吧，把我给吓一跳

**Comment by diyigemt** [comment]
毕竟我又没法让插件用户自己升级
