### ISSUE TITLE
建议向：添加类似'/攻略 杂图'的帮助图和指令

### ISSUE THREAD

**Issue by Goldmifan** [diyigemt/arona#6]
希望能搞一下帮助图，类似“/攻略 杂图”的指令和图片，群里群友们上手比较难，指令不太熟

群友用了一段时间感觉还是非常好的，在此感谢ヾ(•ω•`)o

**Comment by diyigemt** [comment]
用户手册在写了(新建文件夹
如果需要更好的提示可以试试[这个插件](https://mirai.mamoe.net/topic/1685/%E6%9B%B4%E5%A5%BD%E7%9A%84%E5%B8%AE%E5%8A%A9%E8%8F%9C%E5%8D%95-%E6%8B%AF%E6%95%91%E5%8A%A0%E5%85%A5%E5%BE%88%E5%A4%9A%E6%8F%92%E4%BB%B6%E6%97%B6-help-%E6%8C%87%E4%BB%A4%E7%9A%84%E4%BD%93%E9%AA%8C)
以及这玩意功能也不多，用得最多的也就`/攻略`了，剩下的塔罗牌十连也没了

**Comment by Goldmifan** [comment]
好的，感谢
