### ISSUE TITLE
没给任何权限，私聊仍会响应

### ISSUE THREAD

**Issue by Atomseek** [diyigemt/arona#8]
本来是想单独给某个群使用的，但是发现好友私聊也会有响应。
我在配置文件中删除服务群和管理员账号，删除一切权限，但是私聊仍然会响应。
测试结果如下

![Screenshot_20230302_150638](https://user-images.githubusercontent.com/67729048/222355762-0e48e510-6fb8-4cea-8e5d-1c42bdccdb07.png)

**Comment by diyigemt** [comment]
![(OMOZJ_$DRBT}B$3D HDJIE](https://user-images.githubusercontent.com/41864956/222488577-b126c790-2cef-4adb-9bd3-ede7aa3a36e5.jpg)

**Comment by diyigemt** [comment]
就，我在想一个问题嗷，如果一个群没有使用权限，但是群友又想用，于是私聊试试看，发现能用，很欣喜，而且私聊也不会影响其他群友。
那么不给他用的原因是什么呢。
所以我在想这究竟是个bug，还是一个enhancement

**Comment by Atomseek** [comment]
> 就，我在想一个问题嗷，如果一个群没有使用权限，但是群友又想用，于是私聊试试看，发现能用，很欣喜，而且私聊也不会影响其他群友。 那么不给他用的原因是什么呢。 所以我在想这究竟是个bug，还是一个enhancement

因为我的机器人安装了gpt插件，私聊的话会以为你在问gpt，比如/活动 会同时响应阿罗那插件和gpt插件

**Comment by pilgrim773** [comment]
> 就，我在想一个问题嗷，如果一个群没有使用权限，但是群友又想用，于是私聊试试看，发现能用，很欣喜，而且私聊也不会影响其他群友。 那么不给他用的原因是什么呢。 所以我在想这究竟是个bug，还是一个enhancement

私聊毕竟不在光天化日之下，还是有些用户想避免的吧。
我就不是很喜欢bot被人私聊，所有功能都是群消息才响应

**Comment by diyigemt** [comment]
fix at [1.0.14+20230310](https://github.com/diyigemt/arona/releases/tag/v1.0.14%2B20230310)

**Comment by Atomseek** [comment]
> fix at [1.0.14+20230310](https://github.com/diyigemt/arona/releases/tag/v1.0.14%2B20230310)

禁了但没完全禁，比如我打活动依旧会发图片
![Screenshot_20230313_153937](https://user-images.githubusercontent.com/67729048/224637178-c0c45c46-9298-4260-8b94-8a79e5c213f1.png)

**Comment by diyigemt** [comment]
啊哈哈

**Comment by diyigemt** [comment]
fix at [1.0.14+20230325](https://github.com/diyigemt/arona/releases/tag/v1.0.14%2B20230325)

**Comment by Atomseek** [comment]
彳亍 了
