### ISSUE TITLE
下载攻略图片失败，并报错

### ISSUE THREAD

**Issue by Nohara3** [diyigemt/arona#9]
![1678355489341](https://user-images.githubusercontent.com/124423679/223985837-8cd8836d-e482-4d03-b056-79ea9eb2f354.jpg)
![1678355535638](https://user-images.githubusercontent.com/124423679/223985899-b7b8e4ba-3334-4d9e-a61c-e5364f10d75a.jpg)
![image](https://user-images.githubusercontent.com/124423679/223986251-ad8dd49b-414d-4992-8934-b3540f14e269.png)

**Comment by diyigemt** [comment]
看起来像是网络波动或者代理造成的，其他图片正常吗

**Comment by Nohara3** [comment]
其他图片正常，但比如新春狙，使用新春狙作为关键词时，多次提示下载失败，换成春晴奈关键词后就正常显示了

**Comment by diyigemt** [comment]
> 其他图片正常，但比如新春狙，使用新春狙作为关键词时，多次提示下载失败，换成春晴奈关键词后就正常显示了

尝试找一下本地mcl下data/net.diyigemt.arona/image/student_rank/新春狙.png有没有这个文件，有的话删掉试试
